### ISSUE TITLE
Error: -2

### ISSUE THREAD

**Issue by ianflanagan1** [macherel/Connect-IQ-QR-Code-Viewer#1]
Thanks for making this widget!
I'm using on Forerunner 935
Input 3 test URLs in the settings
Whichever I choose on the watch, it shows the label, no QR. Then the label disappears, replaced by: -2
Connection to the phone seems ok (can change the labels and URLs in settings)

**Comment by bartatwork** [comment]
I have been looking for a widget like this for a long time! Thanks for the effort!
Unfortunately, I seem to have about the same issue as described above. I can set labels and values in the app, but the widget on my Vivoactive HR displays "0" instead of a qr code.

**Comment by macherel** [comment]
The label appear while the QR Code is loading.
If a message appears instead of the QR Code, there was an error while loading the QR Code and the number and the number corresponds to an error code.
I've never seen error code "-2" before. It correspond to "BLE_HOST_TIMEOUT"
Can you verify that the data connection is working properly on your phone ?

Note that the widget needs a valid data connection (to internet) through the phone.

**Comment by macherel** [comment]
Concerning the error code "0", I have already had this error when the phone has no data connection.

Check that you have an active data connection on the phone.

PS: please open new thread for new problem

**Comment by ianflanagan1** [comment]
I also saw "0" occasionally. 

I'm new to Garmin. I assume if I can download apps and sync them to the watch that means the phone as a data connection at that time.

The problem could be I'm in China and the URL it needs is blocked (google or something), but I tried on a VPN and still didn't work.

**Comment by macherel** [comment]
I think you are right.
I'm also new in Garmin applications developpement. So I don't understand very well all errors that occur.

The URL that is called is looking something like that : [https://chart.googleapis.com/chart?cht=qr&chl=QRCodeViewer&chs=240x240&choe=UTF-8&chld=L|2](https://chart.googleapis.com/chart?cht=qr&chl=QRCodeViewer&chs=240x240&choe=UTF-8&chld=L|2)
You can try this link directly on your phone to check if it is blocked or not.

I currently do not see any solution but I'm thinking about finding other solutions.

**Comment by macherel** [comment]
I've submited a new version (0.0.5) in which I changed URL used to generate QR code.
You can also customize this URL if you want to change it because it doesn't work.

Thank you for giving a feedback on these changes hoping that your problems are solved
