### ISSUE TITLE
Only displaying "0"

### ISSUE THREAD

**Issue by bartatwork** [macherel/Connect-IQ-QR-Code-Viewer#2]
Again, thanks for building this widget. Please allow me to explain some more on the issue of the widget only displaying "0". 

- My iPhone does have a data and/or wifi connection
- All permissions are set correct; location, refresh in background, etc
- Permission for widget is set; it has permission to use phones data connection
- Other apps or widgets on my Vivoactive HR that need to use my phones data connection work as they should

Unfortunately, the QR widget keeps on displaying a 0, no matter which of the entries I select. I do see the label shortly, but it changes to the 0 after about a second. No difference if I force the use of wifi or mobile data...

Let me know if you need any more details.

**Comment by macherel** [comment]
"0" means UNKNOWN_ERROR
Unfortunately, I do not know how to get more information.
According to the information you give, everything should work properly.
As I already said, I only met your mistake when the phone has no longer internet connection.

I am currently working on an "offline" version of this application that could solve your problems (and many others). However, I am having difficulties and not enough time to release this new version quickly.

**Comment by macherel** [comment]
I've submited a new version (0.0.5) in which I changed URL used to generate QR code.
You can also customize this URL if you want to change it because it doesn't work.

Thank you for giving a feedback on these changes hoping that your problems are solved
