### ISSUE TITLE
Offline support

### ISSUE THREAD

**Issue by IGx89** [macherel/Connect-IQ-QR-Code-Viewer#5]
Hello! Any interest in me contributing code to allow this widget to function offline, without any dependency on a webservice? I have a very rough version working on my Fenix 5 Plus. It has a few limitations (only numbers currently and fewer devices supported, primarily) but already is working much better for me.

**Comment by macherel** [comment]
Hi,
Offline mode is the big missing feature of this widget
I will be glad that other people can contribute to this widget, especially if it is to create an offline version

**Comment by IGx89** [comment]
Great to hear! Currently polishing it up and testing different configurations, and will then submit a PR when I feel confident enough with it. You can take a look at what I've done so far here if you like: https://github.com/IGx89/Connect-IQ-QR-Code-Viewer/tree/feature/offline-qr-codes

**Comment by IGx89** [comment]
Follow-up question for you: since the offline logic won't support as many devices as the current app (CIQ 2 minimum, plus watchdog counter of 120000 or higher), how would you like me to handle that? Remove unsupported devices, or keep the HTTP service approach in as a fallback option for those older devices?

**Comment by IGx89** [comment]
It actually looks like it'll be even trickier still supporting older devices. It's (just barely?) too big to fit into the 64k widget memory limit that some of the older devices have too.

Edit: I may have a solution. One multi-dimensional int array is somehow taking ~14k of memory just existing! Should be a way to optimize that...

**Comment by macherel** [comment]
I took a look at the code you wrote.
You did a great job!
As you may have noticed, your code can not work on older watches.
Unfortunately, I have a forerunner watch and your code can not be compiled for this device.
I don't think it is possible to use your code for modern watch and create fallback for others (compilation error).

I think the best solution is to create two version of the widget, one for Connect IQ 1 compatible devices and another for Connect IQ 2 compatible device.
There's many improvement in SKD for Connect IQ 2, it would be a shame not to take advantage of it.

I can help you to improve the Connect IQ 2 compatible widget.

**Comment by IGx89** [comment]
Thanks! I could fix the compilation error by either removing the use of ByteArray's (assuming memory usage doesn't increase too much) or using the jungle file's conditional compilation feature to individually customize the builds for each device. But yeah, it's definitely feeling more and more like this would be better as a separate widget. Very little code is shared between the two methods, and production support would get tricky if both were in the same widget.

If you're cool with that, I probably will move down the separate widget route. I'll definitely make sure to credit you and have all the code on GitHub. It's mainly just been a way to help me learn Connect IQ's platform and language limitations.

On a different note, I bet offline support for your widget could be achieved a much simpler way, by caching the QR code image's bit array in persistent storage and building the image from that every time. In hindsight I probably would have gone that route, much easier :p.

**Comment by macherel** [comment]
As we agreed by email, I can't use your solution due to some devices restrictions.
Luckily, I just find another way to have offline support
Now data connexion is needed only at first startup or when QR codes are changed.

**Comment by IGx89** [comment]
Oh great! Sounds like you went down the caching route then. Looking forward to checking it out!

**Comment by macherel** [comment]
Yes
I can't cache directly image, so I convert image to text using a php script I made.
Then this text is convert to image using a custom font. I use this trick because drawing each pixel manually is not enough performant
