### ISSUE TITLE
How to add a Vcard?

### ISSUE THREAD

**Issue by clyra** [macherel/Connect-IQ-QR-Code-Viewer#7]
Hi,

How to add a vcard to widget? The vcard format can be viewed here (https://en.wikipedia.org/wiki/VCard), but I couldnt find a way to transform this format on a string to be inserted on the garmin mobile app. (ex: BEGIN:VCARD VERSION:3.0 N:Gump;Forrest;;Mr.; FN:Forrest Gump END: VCARD). I also tried by inserting \n to the end of each field but didnt worked either. Am I missing something?

**Comment by macherel** [comment]
Hi,

To add a VCard to the widget, you currently have to copy the string corresponding to the VCard (including the line breaks) and paste it into a QR code value in settings.
Please note that there is an issue on iOS garmin connect app that remove line breaks when you past a string in settings. As a workaround, I've made a web app to manage QR code.
This web app  currently handle strings only (so you can copy/paste your VCard as string) but I'm working a VCard editor.
This web application is accessible here: https://data-manager.qrcode.macherel.fr/ but needs a valid token to use it.
