### ISSUE TITLE
How to add barcode? 

### ISSUE THREAD

**Issue by tronderbataljon** [macherel/Connect-IQ-QR-Code-Viewer#8]
According to latest update, I should be able to add regular barcode to the widget, which is awesome. But I have no idea how to do it? Garmin Vivoactive 4s

**Comment by macherel** [comment]
As I've reply by mail, barcodes can be added only with [the web interface](https://data-manager.qrcode.macherel.fr/)
When you edit a code with the web interface, you can choose the type of the code (QR code, Aztec or EAN). Barcode correspond to the EAN type, there is EAN-13 for code having 13 numeric digit or EAN-128 for alphanumeric codes.
To do that you need a valid token that you fill both in the web interface and in the widget settings (you also need to enable external data in the widget settings)
The token "demo" can be used to test this feature.
