### ISSUE TITLE
Barcode is unusable tiny

### ISSUE THREAD

**Issue by alexanderadam** [macherel/Connect-IQ-QR-Code-Viewer#9]
I just tried your QR code viewer but it seems that there's a problem with scaling?

This is on a Garmin Forerunner 945 and `pdf417`.

![Tiny QR Code](https://user-images.githubusercontent.com/372620/91580336-3807a480-e94d-11ea-9623-ab72ddc3caf7.png)

**PS:** Thank you for your work!

**Comment by macherel** [comment]
I'm very sorry for my very late response.
I can't do anything to have a bigger code. If each square is 1 pixel
bigger, your code goes out of the screen.
You can try to put 400 or 500 in the "size" field in settings but I think
your code will be too big.

**Comment by ara-ler** [comment]
I have the same problem here. By the way, does the size setting work only with "unlocked" functionality (with token)?
@alexanderadam , I heard, Code 39 works for Starbucks.

**Comment by alexanderadam** [comment]
> does the size setting work only with "unlocked" functionality (with token)?

I can confirm that the `size` setting doesn't seem to change anything for me either.

> I heard, Code 39 works for Starbucks

This looks great. Thank you :+1:

**Comment by ara-ler** [comment]
> I can't do anything to have a bigger code. If each square is 1 pixel bigger, your code goes out of the screen.
Formally you're right, @macherel , but practically 2D barcode's readability requirements are pretty flexible.
Take a look at [https://apps.garmin.com/en-US/apps/6606530f-68e5-4ba7-885c-f8dba4268cee](url), it's woking great.

**Comment by macherel** [comment]
sorry (again) for my late response

@ara-ler a token will not change anything at this problem.

I have a new idea to fix the problem (on recent watch), I hope this will work.

**Comment by macherel** [comment]
I was totally wrong, it can works without any modification and the idea I had does not work.
Some explanation...
For now, the only solution I found is to produce an image remotely (and I can't store it locally). So you have to disable the "offline mode" in settings.
There was also a limitation that prevent to produce this image without a token. I just remove this limitation so you can display your code
